internetShop/Controllers/CarsController.cs
using internetShop.Interfaces;
using internetShop.Models;
using internetShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace internetShop.Controllers
{
    public class CarsController : Controller
    {
        private readonly IAllCars _allCars;
        private readonly ICarsCategory _allCategories;

        public CarsController(IAllCars IallCars, ICarsCategory IcarsCategories)
        {
            _allCars = IallCars;
            _allCategories = IcarsCategories;
        }

        [Route("Cars/List/")]
        [Route("Cars/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Car> cars;
            string currCategory = "";

            if (string.IsNullOrEmpty(category)){
                cars = _allCars.Cars.OrderBy(i => i.id);
            }
            else
            {
                if (string.Equals("Sedan", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars
                        .Where(i => i.categoryID == 2)
                        .OrderBy(i => i.id);
                }
                else
                {
                    cars = _allCars.Cars.Where(i => i.categoryID == 1)
                        .OrderBy(i => i.id);                    
                }
                currCategory= _category;
            }

            var carObj = new CarsListViewModel
            {
                allCars = cars,
                carCategory = currCategory,
            };

            ViewBag.Title = "Car's Page";

            return View(carObj);
        }
    }
}

internetShop/Controllers/OrderController.cs
using internetShop.Interfaces;
using internetShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace internetShop.Controllers
{
    public class OrderController :Controller
    {
        private readonly IAllOrders _allOrders;
        private readonly ShopCart _shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            _allOrders = allOrders;
            _shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            _shopCart.listShopItems = _shopCart.GetCartItems();

            if(_shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("","You must have items");
            }

            if(ModelState.IsValid)
            {
                _allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Your order successfully processed";
            return View();
        }
    }
}

internetShop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using internetShop.Models;
using internetShop.ViewModels;
using internetShop.Interfaces;

namespace internetShop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllCars carRep, ShopCart shopCart)
        {
            _carRep = carRep;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.GetCartItems();
            _shopCart.listShopItems = items;


            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart,
            };
            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _carRep.Cars.FirstOrDefault(i => i.id == id);
            if(item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

internetShop/Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
    <h2>Model: @Model.name</h2>
    <p>Price: @Model.price.ToString("c")</p>
    <p><a class="btn btn-dark" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Add to Cart</a></p>
</div>

internetShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>    
    <link href="~/css/site.css" rel="stylesheet" type="text/css"/>
</head>
<body>
    <header class="d-flex justify-content-center py-3">
      <ul class="nav nav-pills">
        <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a asp-controller="Cars" asp-action="List" class="nav-link">Cars</a></li>
        <li class="nav-item"><a href="/Cars/List/Sedan" class="nav-link">Sedan</a></li>
        <li class="nav-item"><a href="/Cars/List/Sports" class="nav-link">Sport's</a></li>
        <li class="nav-item"><a asp-controller="Order" asp-action="Checkout" class="nav-link">Cart</a></li>
      </ul>
    </header>
    <div calss="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <br />
        <p>© 2023 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a> · <a class="float-end" href="#">Back to top</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>